### ISSUE TITLE
can't delete the directory of node_modules on windows7

### ISSUE THREAD

**Issue by ReySun** [exequiel09/fastify-angular-universal#2]
#### screenshot
![image](https://user-images.githubusercontent.com/20747990/34820394-62537b98-f6fb-11e7-8a33-48093cd1ff48.png)

#### maybe due to this line
https://github.com/exequiel09/fastify-angular-universal/blob/master/test-app/package.json#L33

**Comment by exequiel09** [comment]
I have no windows machine on me right now. But i know it's because of that line that it has nested `test-app` folder. That is only for testing purposes nothing more.

**Comment by exequiel09** [comment]
I have a windows 8.1 virtual machine (sorry i dont have windows 7 as of now), i can delete those folders. Does it cause unwanted issue to the behaviour of the plugin?

**Comment by ReySun** [comment]
nothing. the plugin Work normally!
i find this bug due to [cnpm](https://npm.taobao.org/package/cnpm), it's ok when i use `npm` or `yarn`.
thank you!
